steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/utopian-planet-485618-b3/hw9-repo/hw9-webserver:latest', '.']
images:
- 'us-central1-docker.pkg.dev/utopian-planet-485618-b3/hw9-repo/hw9-webserver:latest'
options:
  logging: CLOUD_LOGGING_ONLY
